### ISSUE TITLE
Import Renault database into application

### ISSUE THREAD

**Issue by igogo2** [uholeschak/ediabaslib#143] opened 2023-02-15 12:03 UTC
It will be grate to extend functionality of the application. I have a BMW and Renault cars as example.
Now i use [Pyren](https://gitlab.com/py_ren/pyren) application for it. But it works only on Windows PC. I guess it doesn't cost much to import logic from Pyren to Deep OBD.  [Here](https://drive.google.com/drive/folders/1AdZB_8Lm9YBD10b7ycl1iBikJkktYJy3) we can find Clip and DDT2000 databases for example.

**Comment by uholeschak** [comment] 2023-02-15 12:08
Interesting, but from where to get the databases?
Are there also databases from other manufacturers?
At least this is really much work. Would you pay for this?

**Comment by uholeschak** [comment] 2023-02-15 13:07
I will close it for now. After providing databases, database specification and protocol specification I could check this again.

**Comment by igogo2** [comment] 2023-02-15 15:01
Regarding protocols. Renault + Nisan + Dacia uses [ISO 14230 KWP4](https://en.wikipedia.org/wiki/Keyword_Protocol_2000) K-line and CAN versions (Slow, Fast) and [ISO 15765-4 CAN (11 bit ID,500 Kbaud)](https://en.wikipedia.org/wiki/ISO_15765-2). Those protocols a already implemented in ELM327 and Deep OBD knows them. [Here ](https://www.atbs.com.tw/product%20spec/WEB/CAR/support%20list.pdf)you can find a model + protocol relation.

Regarding databases. [This is](https://drive.google.com/file/d/1oV0xfM5eL88-RGGw3WQ7YTZcHyEFS-0R/view?usp=share_link) a clip database with all data. It is a part of official dealer's diagnostic tool. This databases are present in internet.

Regarding specifications of the database contents. Maybe you should look into [mod_optfile.py ](https://gitlab.com/py_ren/pyren/-/blob/master/pyren/mod_optfile.py)- for exploring CLIP database and [mod_ecu.py](https://gitlab.com/py_ren/pyren/-/blob/master/pyren/mod_ecu.py) - shows list of all parameters, commands and DTCs. Build "PID" CSV file for "Torque PRO".

**Comment by uholeschak** [comment] 2023-02-15 15:12
An where to I get the C content for the DDT2000data directory from?

**Comment by uholeschak** [comment] 2023-02-15 16:25
If you have already so much insight i would be probably the best solution you implement it in the app.

**Comment by igogo2** [comment] 2023-02-15 16:40
DDT2000data is other application which do the same in other way (other official tool which is used on plant). Forget about it. Apologies for confusing you.
Sorry. I'm not interested in payment now. Personally i'm using Pyren application and it do what i want. I'm writing because i want to help you improve/extend your application.
I'm beginner at programming, but i will try to create a patch. It will be a good chance to train myself.

**Comment by uholeschak** [comment] 2023-02-15 16:41
This would be helpful. The problem is my time is very limited.

**Comment by igogo2** [comment] 2023-02-15 17:02
Other example.
Data is taken from the BVMEXTRACTION database for a specific VIN. As example, go to the X95 folder. Here are all possible configurations of ECUs (REF.dat) and all possible combination of options (MTC.dat) in text form.
Next, take your VIN and the first 3 letters after VF1. Than find the desired directory. After that, we take the next 6 letters of the VIN and look at what range they fall into, for example, between KZ0RD2 and VZR7T5З, so we need KZ0RD2.dat. Rename it to KZ0RD2.zip and unzip it. We select a file with our next 6 letters. Inside we are looking for a line starting with the last letters of our VIN, the second number in this line is a link to the MTC.dat file and the third number (without leading zeros) is a link to REF.dat
Dialogys\data\langue\en\classicvar.utf (utf-8 encoding, plain text.) here we search for the necessary MTC.

**Comment by uholeschak** [comment] 2023-02-15 17:04
Thanks for the info.
But finally a vehicle simulation is required to test the communication.

**Comment by uholeschak** [comment] 2023-02-15 23:15
Perhaps we could wait if more people vote for this. If it reaches a critical market level it could get interesting.

**Comment by mi-hol** [comment] 2023-02-20 07:47
@uholeschak to have visibility and allow for voting, re-opening the issue is a pre-requisite!

**Comment by igogo2** [comment] 2023-02-20 09:25
I will help with connection to the car. But not now. Very busy.

**Comment by uholeschak** [comment] 2023-02-20 09:28
Basically various traces of the OBD communications of the existing software is required to simulate this.

**Comment by uholeschak** [comment] 2023-11-05 21:48
Closed because of no response.

**Closed by uholeschak** 2023-11-05 21:48 UTC
